const DEFAULT_IMG='assets/hero-yoga.jpg', DB_NAME='YogaConRocioDB', STORE='media';
const seed={
 videos:[
  {id:'v1',title:'Morning Reset',description:'A gentle full-body practice to wake up with more space and energy.',duration:15,level:'Beginner',category:'Morning',access:'Free',image:DEFAULT_IMG,videoKey:null,published:true},
  {id:'v2',title:'Strong & Grounded',description:'A steady practice for core strength, balance and confidence.',duration:24,level:'Intermediate',category:'Strength',access:'Member',image:DEFAULT_IMG,videoKey:null,published:true},
  {id:'v3',title:'Hip Release',description:'Slow mobility for hips, glutes and lower back.',duration:18,level:'Beginner',category:'Mobility',access:'Member',image:DEFAULT_IMG,videoKey:null,published:true},
  {id:'v4',title:'Evening Unwind',description:'A calming sequence to soften the body and close the day.',duration:22,level:'All levels',category:'Rest',access:'Free',image:DEFAULT_IMG,videoKey:null,published:true},
  {id:'v5',title:'Power Flow',description:'A dynamic vinyasa for energy, heat and focus.',duration:30,level:'Intermediate',category:'Vinyasa',access:'Member',image:DEFAULT_IMG,videoKey:null,published:true}
 ],
 shop:[
  {id:'s1',type:'Program',title:'7-Day Morning Reset',subtitle:'Seven short guided practices',price:39,image:DEFAULT_IMG},
  {id:'s2',type:'Object',title:'Cork Yoga Block',subtitle:'Support, stability and comfort',price:24,image:DEFAULT_IMG},
  {id:'s3',type:'Clothing',title:'Soft Flow Set',subtitle:'Comfort made for movement',price:89,image:DEFAULT_IMG},
  {id:'s4',type:'Beauty',title:'Evening Ritual Oil',subtitle:'Lavender and jojoba blend',price:28,image:DEFAULT_IMG}
 ],
 articles:[
  {tag:'RITUAL',title:'A five-minute morning that changes the tone of your day',text:'A simple combination of breath, spinal movement and one quiet intention.',cta:'Read the ritual'},
  {tag:'JOURNAL',title:'Why consistency matters more than flexibility',text:'Your practice does not need to look perfect. It only needs a place in your life.',cta:'Read the note'},
  {tag:'GUIDE',title:'How to choose the right practice for your energy',text:'Learn when to move strongly, when to slow down and when rest is the practice.',cta:'Open the guide'}
 ],
 favourites:['v3'],completed:['v1'],heroImage:DEFAULT_IMG,
 activity:{steps:6842,walking:4.8,running:1.6,practice:32,streak:4}
};
let state=loadState(),selectedShopType='Program',exploreFilter='all';
function loadState(){try{return {...structuredClone(seed),...JSON.parse(localStorage.getItem('ycr-state-v3')||'{}')}}catch{return structuredClone(seed)}}
function save(){localStorage.setItem('ycr-state-v3',JSON.stringify(state))}
function route(){return(location.hash||'#home').slice(1).split('/')}
function navigate(path){location.hash='#'+path}
function toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),2100)}
function money(n){return`CHF ${Number(n).toFixed(0)}`}
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putMedia(k,f){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(f,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getMedia(k){if(!k)return null;const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function fileToDataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function topbar(active){const nav=[['home','Home'],['explore','Explore'],['shop','Studio shop'],['practice','My practice']];return`<header class="topbar"><a class="brand" href="#home"><span class="brand-mark">YR</span><span>Yoga con <em>Rocío</em></span></a><nav>${nav.map(([r,l])=>`<a class="${active===r?'active':''}" href="#${r}">${l}</a>`).join('')}</nav><a class="creator-link" href="#admin">Creator access</a></header>`}
function mobileNav(active){return`<nav class="mobile-nav">${[['home','⌂','Home'],['explore','⌕','Explore'],['shop','◇','Shop'],['practice','◌','Practice']].map(([r,i,l])=>`<a class="${active===r?'active':''}" href="#${r}"><span>${i}</span>${l}</a>`).join('')}</nav>`}
function layout(content,active,scroll=false){return`<div class="app-shell ${scroll?'home-scroll':''}">${topbar(active)}<main class="screen ${scroll?'scroll-screen':''}">${content}</main>${mobileNav(active)}</div>`}
function classCard(v,cls=''){return`<article class="class-card ${cls}" onclick="navigate('watch/${v.id}')"><img src="${v.image||DEFAULT_IMG}" alt="${v.title}"><div class="shade"></div><div class="card-overlay"><span>${v.category} · ${v.duration} min</span><h3>${v.title}</h3><div><small>${v.level}</small><button aria-label="Play">▶</button></div></div></article>`}
function home(){const f=state.videos[0];return layout(`<section class="home-hero"><img src="${state.heroImage}"><div class="hero-wash"></div><div class="hero-copy"><span class="eyebrow light">YOGA · MOVEMENT · RITUAL</span><h1>Come home<br>to yourself.</h1><p>Thoughtful yoga practices with Rocío for strength, calm and a more connected everyday life.</p><div class="hero-actions"><button class="primary light-btn" onclick="navigate('watch/${f.id}')">Start today <span>→</span></button><a href="#explore">Explore classes</a></div></div><div class="hero-note"><span>Today’s practice</span><b>${f.title}</b><small>${f.duration} min · ${f.level}</small></div></section>
<section class="home-section intro"><span class="eyebrow">YOGA CON ROCÍO</span><h2>A softer way to build a stronger practice.</h2><p>Choose a class for the time and energy you have today. No pressure, no complicated plans—just a clear place to begin.</p></section>
<section class="home-section"><div class="section-head"><div><span class="eyebrow">THIS WEEK</span><h2>Practices for you</h2></div><a href="#explore">View all →</a></div><div class="home-class-grid">${state.videos.slice(0,3).map((v,i)=>classCard(v,i===0?'wide-card':'')).join('')}</div></section>
<section class="sage-band"><div><span class="eyebrow light">SIGNATURE PROGRAM</span><h2>7 mornings.<br>One new rhythm.</h2><p>Short guided practices designed to help you begin the day with clarity and consistency.</p><button class="cream-btn" onclick="selectShop('Program');navigate('shop')">Discover the program</button></div><img src="${state.heroImage}"></section>
<section class="home-section"><div class="section-head"><div><span class="eyebrow">READ & REFLECT</span><h2>From Rocío’s journal</h2></div></div><div class="article-grid">${state.articles.map(a=>`<article><span>${a.tag}</span><h3>${a.title}</h3><p>${a.text}</p><button onclick="toast('Article preview')">${a.cta} →</button></article>`).join('')}</div></section>
<footer><div class="brand"><span class="brand-mark">YR</span><span>Yoga con <em>Rocío</em></span></div><p>Move with intention. Live with presence.</p></footer>`,'home',true)}
function explore(){return layout(`<section class="module-layout"><header class="module-head"><div><span class="eyebrow">VIDEO LIBRARY</span><h1>Explore</h1></div><label class="search">⌕<input id="search" placeholder="Search practices" oninput="filterExplore()"></label></header><div class="filter-line"><button class="chip active" onclick="setExploreFilter(this,'all')">All</button>${['Morning','Strength','Mobility','Rest','Vinyasa'].map(x=>`<button class="chip" onclick="setExploreFilter(this,'${x}')">${x}</button>`).join('')}</div><div id="explore-grid" class="explore-grid">${state.videos.filter(v=>v.published).map(v=>classCard(v)).join('')}</div></section>`,'explore')}
window.setExploreFilter=(el,f)=>{exploreFilter=f;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));el.classList.add('active');filterExplore()};
window.filterExplore=()=>{const q=(document.querySelector('#search')?.value||'').toLowerCase();const list=state.videos.filter(v=>v.published&&(exploreFilter==='all'||v.category===exploreFilter)&&(!q||(v.title+' '+v.description).toLowerCase().includes(q)));document.querySelector('#explore-grid').innerHTML=list.map(v=>classCard(v)).join('')||'<div class="empty">No practices found.</div>'};
function shop(){const types=['Program','Object','Clothing','Beauty'],items=state.shop.filter(x=>x.type===selectedShopType);return layout(`<section class="module-layout"><header class="module-head"><div><span class="eyebrow">CURATED BY ROCÍO</span><h1>Studio shop</h1></div><p class="module-note">Programs and thoughtful essentials for your practice.</p></header><div class="shop-tabs">${types.map(t=>`<button class="${selectedShopType===t?'active':''}" onclick="selectShop('${t}')">${t}${t==='Program'?'s':''}</button>`).join('')}</div><div class="shop-stage">${items.map(x=>`<article class="shop-card"><div class="shop-image"><img src="${x.image}"><span>${x.type}</span></div><div class="shop-copy"><div><span class="eyebrow">YOGA CON ROCÍO</span><h2>${x.title}</h2><p>${x.subtitle}</p></div><div class="shop-buy"><strong>${money(x.price)}</strong><button onclick="toast('Added to your bag')">Add to bag</button></div></div></article>`).join('')}</div></section>`,'shop')}
window.selectShop=t=>{selectedShopType=t;render()};
function practice(){const recent=state.videos.slice(0,3);return layout(`<section class="practice-layout"><header class="module-head"><div><span class="eyebrow">YOUR SPACE</span><h1>My practice</h1></div><div class="sync-pill">Wellness overview</div></header><div class="practice-grid"><article class="activity-panel"><div class="panel-title"><div><span class="eyebrow">TODAY</span><h2>Daily movement</h2></div><button onclick="editActivity()">Edit</button></div><div class="activity-main"><div class="ring"><div><b>${state.activity.steps.toLocaleString()}</b><small>steps</small></div></div><div class="activity-list"><p><span>Walking</span><b>${state.activity.walking} km</b></p><p><span>Running</span><b>${state.activity.running} km</b></p><p><span>Yoga</span><b>${state.activity.practice} min</b></p></div></div><div class="week-row">${['M','T','W','T','F','S','S'].map((d,i)=>`<div><span class="${i<4?'done':''}">${i<4?'✓':''}</span><small>${d}</small></div>`).join('')}</div></article><article class="continue-panel"><div class="panel-title"><div><span class="eyebrow">CONTINUE</span><h2>Your next practice</h2></div><span>${state.activity.streak} day streak</span></div>${classCard(recent[1],'featured')}</article><article class="saved-panel"><div class="panel-title"><div><span class="eyebrow">SAVED</span><h2>For later</h2></div><a href="#explore">See all</a></div><div class="saved-list">${recent.map(v=>`<button onclick="navigate('watch/${v.id}')"><img src="${v.image}"><span><b>${v.title}</b><small>${v.duration} min · ${v.category}</small></span><i>▶</i></button>`).join('')}</div></article></div></section>`,'practice')}
window.editActivity=()=>{const value=prompt('Today’s steps',state.activity.steps);if(value!==null&&!isNaN(value)){state.activity.steps=Number(value);save();render()}};
async function watch(id){const v=state.videos.find(x=>x.id===id)||state.videos[0];let media=`<div class="video-placeholder" style="background-image:linear-gradient(rgba(20,34,25,.22),rgba(20,34,25,.55)),url('${v.image}')"><button>▶</button><p>Upload a class video in Creator access<br>to preview it here.</p></div>`;if(v.videoKey){const f=await getMedia(v.videoKey);if(f)media=`<video controls playsinline poster="${v.image}" src="${URL.createObjectURL(f)}"></video>`}document.querySelector('#app').innerHTML=layout(`<section class="watch-page"><a class="watch-back" href="#explore">← Explore</a><div class="watch-layout"><div class="watch-player">${media}</div><aside class="watch-info"><span class="eyebrow">${v.category.toUpperCase()}</span><h1>${v.title}</h1><p>${v.description}</p><div class="watch-meta"><span>${v.duration} min</span><span>${v.level}</span><span>${v.access}</span></div><div class="teacher"><div class="avatar">R</div><div><small>GUIDED BY</small><b>Rocío</b></div></div><button class="primary wide" onclick="completeVideo('${v.id}')">${state.completed.includes(v.id)?'Completed ✓':'Mark as complete'}</button><div class="up-next"><small>UP NEXT</small>${state.videos.filter(x=>x.id!==v.id).slice(0,2).map(x=>`<button onclick="navigate('watch/${x.id}')"><img src="${x.image}"><span><b>${x.title}</b><small>${x.duration} min · ${x.level}</small></span><i>→</i></button>`).join('')}</div></aside></div></section>`,'explore')}
window.completeVideo=id=>{if(!state.completed.includes(id))state.completed.push(id);save();toast('Practice completed');render()};
function side(active){return`<aside class="creator-side"><a class="brand dark" href="#home"><span class="brand-mark">YR</span><span>Yoga con <em>Rocío</em></span></a><nav>${[['admin','Overview'],['admin/videos','Classes'],['admin/shop','Shop'],['admin/brand','Brand']].map(([r,l])=>`<a class="${active===r?'active':''}" href="#${r}">${l}</a>`).join('')}</nav><a class="back-site" href="#home">← View website</a></aside>`}
function admin(){return`<div class="creator-shell">${side('admin')}<main class="creator-main"><header><div><span class="eyebrow">CREATOR ACCESS</span><h1>Overview</h1></div><button class="primary" onclick="navigate('admin/new')">+ Add class</button></header><div class="creator-stats"><div><span>Published classes</span><b>${state.videos.filter(v=>v.published).length}</b></div><div><span>Shop items</span><b>${state.shop.length}</b></div><div><span>Completed sessions</span><b>${state.completed.length}</b></div></div><section class="creator-panel"><div class="panel-title"><div><span class="eyebrow">CONTENT</span><h2>Your classes</h2></div><a href="#admin/videos">Manage all</a></div><div class="creator-list">${state.videos.slice(0,4).map(v=>creatorRow(v)).join('')}</div></section></main></div>`}
function creatorRow(v){return`<button onclick="navigate('admin/edit/${v.id}')"><img src="${v.image}"><span><b>${v.title}</b><small>${v.duration} min · ${v.category}</small></span><em>${v.published?'Published':'Draft'}</em><i>›</i></button>`}
function adminVideos(){return`<div class="creator-shell">${side('admin/videos')}<main class="creator-main"><header><div><span class="eyebrow">CONTENT</span><h1>Classes</h1></div><button class="primary" onclick="navigate('admin/new')">+ Add class</button></header><section class="creator-panel fill"><div class="creator-list large">${state.videos.map(v=>creatorRow(v)).join('')}</div></section></main></div>`}
function adminShop(){return`<div class="creator-shell">${side('admin/shop')}<main class="creator-main"><header><div><span class="eyebrow">COMMERCE</span><h1>Shop</h1></div><button class="primary" onclick="addShopItem()">+ Add item</button></header><section class="creator-panel fill"><div class="shop-admin-grid">${state.shop.map(x=>`<article><img src="${x.image}"><span>${x.type}</span><h3>${x.title}</h3><p>${x.subtitle}</p><b>${money(x.price)}</b></article>`).join('')}</div></section></main></div>`}
window.addShopItem=()=>{const title=prompt('Item name');if(!title)return;state.shop.push({id:'s'+Date.now(),type:'Object',title,subtitle:'New studio item',price:29,image:state.heroImage});save();render();toast('Shop item added')};
function adminBrand(){return`<div class="creator-shell">${side('admin/brand')}<main class="creator-main"><header><div><span class="eyebrow">APPEARANCE</span><h1>Brand</h1></div></header><section class="brand-editor"><div class="brand-preview"><img src="${state.heroImage}"><div><span>Homepage cover</span><h2>Come home to yourself.</h2></div></div><div class="brand-controls"><h2>Homepage image</h2><p>Choose a landscape or vertical image. It updates across the website.</p><input id="brand-file" type="file" accept="image/*"><button class="primary" onclick="saveBrandImage()">Save image</button></div></section></main></div>`}
window.saveBrandImage=async()=>{const f=document.querySelector('#brand-file').files[0];if(!f)return toast('Choose an image first');state.heroImage=await fileToDataUrl(f);save();render();toast('Brand image updated')};
function classForm(id){const v=id?state.videos.find(x=>x.id===id):null;return`<div class="creator-shell">${side('admin/videos')}<main class="creator-main form-page"><header><div><span class="eyebrow">${v?'EDIT':'NEW'} CLASS</span><h1>${v?'Edit class':'Add class'}</h1></div></header><form class="editor-grid" onsubmit="saveClass(event,'${id||''}')"><section class="editor-media"><div class="image-drop"><img id="cover-preview" src="${v?.image||state.heroImage}"><label>Change cover<input id="cover-file" type="file" accept="image/*" onchange="previewCover()"></label></div><div class="video-drop"><span>▶</span><div><b>${v?.videoKey?'Video attached':'Upload class video'}</b><small>MP4, MOV or WebM</small></div><label>Choose file<input id="video-file" type="file" accept="video/*"></label></div></section><section class="editor-fields"><label>Title<input name="title" required value="${v?.title||''}" placeholder="Morning full body flow"></label><label>Description<textarea name="description" rows="3">${v?.description||''}</textarea></label><div class="two"><label>Duration<input name="duration" type="number" min="1" value="${v?.duration||20}"></label><label>Level<select name="level">${['Beginner','Intermediate','All levels'].map(x=>`<option ${v?.level===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="two"><label>Category<select name="category">${['Morning','Strength','Mobility','Rest','Vinyasa'].map(x=>`<option ${v?.category===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Access<select name="access">${['Free','Member'].map(x=>`<option ${v?.access===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label class="publish-row"><input name="published" type="checkbox" ${v?.published!==false?'checked':''}> Publish this class</label><div class="form-actions"><button type="button" class="secondary" onclick="navigate('admin/videos')">Cancel</button><button class="primary">Save class</button></div></section></form></main></div>`}
window.previewCover=()=>{const f=document.querySelector('#cover-file').files[0];if(f)document.querySelector('#cover-preview').src=URL.createObjectURL(f)};
window.saveClass=async(e,id)=>{e.preventDefault();const fd=new FormData(e.target);let v=id?state.videos.find(x=>x.id===id):null;if(!v){v={id:'v'+Date.now(),image:state.heroImage,videoKey:null};state.videos.unshift(v)}const cover=document.querySelector('#cover-file').files[0];if(cover)v.image=await fileToDataUrl(cover);const video=document.querySelector('#video-file').files[0];if(video){v.videoKey='media-'+v.id;await putMedia(v.videoKey,video)}Object.assign(v,{title:fd.get('title'),description:fd.get('description'),duration:Number(fd.get('duration')),level:fd.get('level'),category:fd.get('category'),access:fd.get('access'),published:fd.get('published')==='on'});save();navigate('admin/videos');toast('Class saved')};
async function render(){const[r,a,b]=route(),app=document.querySelector('#app');if(r==='home')app.innerHTML=home();else if(r==='explore')app.innerHTML=explore();else if(r==='shop')app.innerHTML=shop();else if(r==='practice')app.innerHTML=practice();else if(r==='watch')await watch(a);else if(r==='admin'&&!a)app.innerHTML=admin();else if(r==='admin'&&a==='videos')app.innerHTML=adminVideos();else if(r==='admin'&&a==='shop')app.innerHTML=adminShop();else if(r==='admin'&&a==='brand')app.innerHTML=adminBrand();else if(r==='admin'&&a==='new')app.innerHTML=classForm();else if(r==='admin'&&a==='edit')app.innerHTML=classForm(b);else navigate('home')}
window.addEventListener('hashchange',render);window.addEventListener('DOMContentLoaded',render);
