const DEFAULT_IMG = 'assets/hero-yoga.jpg';
const DB_NAME = 'YogaStudioDB';
const STORE = 'media';

const seed = {
  videos: [
    {id:'v1', title:'15-Minute Morning Mobility', description:'Wake up your body with a gentle mobility sequence for hips, shoulders and spine.', duration:15, level:'Beginner', category:'Morning', goal:'Mobility', price:0, access:'Free', image:DEFAULT_IMG, videoKey:null, published:true},
    {id:'v2', title:'Full Body Morning Flow', description:'A bright, energising vinyasa flow to start your day with focus.', duration:20, level:'Intermediate', category:'Vinyasa', goal:'Energy', price:14, access:'Paid', image:DEFAULT_IMG, videoKey:null, published:true},
    {id:'v3', title:'Hip Opening Stretch', description:'Slow, grounded stretches for tight hips and lower back.', duration:18, level:'Beginner', category:'Mobility', goal:'Flexibility', price:9, access:'Paid', image:DEFAULT_IMG, videoKey:null, published:true},
    {id:'v4', title:'Yoga for Better Sleep', description:'A calming evening practice designed to settle the nervous system.', duration:25, level:'Beginner', category:'Restorative', goal:'Better Sleep', price:12, access:'Paid', image:DEFAULT_IMG, videoKey:null, published:true}
  ],
  programs: [
    {id:'p1', title:'7-Day Morning Reset', subtitle:'Build a consistent morning routine in one week.', description:'A guided seven-day journey combining mobility, breath, gentle strength and mindful movement. Each class is short enough to fit into a busy morning.', price:39, level:'Beginner', days:7, image:DEFAULT_IMG, lessonIds:['v1','v2','v3','v4']},
    {id:'p2', title:'21-Day Flexibility Journey', subtitle:'Move with more freedom and less tension.', description:'Progressive sessions focused on hips, hamstrings, spine and shoulders.', price:59, level:'All Levels', days:21, image:DEFAULT_IMG, lessonIds:['v3','v4']}
  ],
  purchases:['p1'], favourites:['v3'], completed:['v1'], progress:{p1:57,p2:18}, heroImage:DEFAULT_IMG
};

let state = loadState();
let objectUrls = [];

function loadState(){
  try { return {...seed, ...JSON.parse(localStorage.getItem('yoga-state')||'{}')}; }
  catch { return structuredClone(seed); }
}
function save(){ localStorage.setItem('yoga-state',JSON.stringify(state)); }
function money(n){ return n===0 ? 'Free' : `CHF ${Number(n).toFixed(0)}`; }
function route(){ return (location.hash || '#home').slice(1).split('/'); }
function navigate(path){ location.hash = '#'+path; }
function toast(msg){ const el=document.createElement('div'); el.className='toast'; el.textContent=msg; document.body.appendChild(el); setTimeout(()=>el.remove(),2600); }
function icon(name){ const map={home:'⌂',explore:'⌕',programs:'▣',practice:'♡',profile:'◎',admin:'⚙',play:'▶',upload:'⇧',video:'▷',dashboard:'◫'}; return map[name]||'•'; }

function openDb(){
  return new Promise((resolve,reject)=>{
    const req=indexedDB.open(DB_NAME,1);
    req.onupgradeneeded=()=>req.result.createObjectStore(STORE);
    req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error);
  });
}
async function putMedia(key,file){ const db=await openDb(); return new Promise((res,rej)=>{ const tx=db.transaction(STORE,'readwrite'); tx.objectStore(STORE).put(file,key); tx.oncomplete=res; tx.onerror=()=>rej(tx.error); }); }
async function getMedia(key){ if(!key)return null; const db=await openDb(); return new Promise((res,rej)=>{ const req=db.transaction(STORE).objectStore(STORE).get(key); req.onsuccess=()=>res(req.result); req.onerror=()=>rej(req.error); }); }
async function deleteMedia(key){ if(!key)return; const db=await openDb(); return new Promise((res,rej)=>{ const tx=db.transaction(STORE,'readwrite'); tx.objectStore(STORE).delete(key); tx.oncomplete=res; tx.onerror=()=>rej(tx.error); }); }
function fileToDataUrl(file){ return new Promise((res,rej)=>{ const r=new FileReader(); r.onload=()=>res(r.result); r.onerror=rej; r.readAsDataURL(file); }); }

function topbar(active='home'){
  const items=[['home','Home'],['explore','Explore'],['programs','Programs'],['practice','My Practice']];
  return `<header class="topbar"><a class="brand" href="#home"><span class="brand-mark">Y</span><span>Yoga <em>with Lina</em></span></a><nav class="nav">${items.map(([r,l])=>`<a class="${active===r?'active':''}" href="#${r}">${l}</a>`).join('')}<a class="${active==='admin'?'active':''}" href="#admin">Admin</a></nav><a href="#profile"><img class="avatar" src="${state.heroImage}" alt="Profile"></a></header>`;
}
function mobileNav(active){ const items=[['home','Home'],['explore','Explore'],['programs','Programs'],['practice','Practice'],['profile','Profile']]; return `<nav class="mobile-nav">${items.map(([r,l])=>`<a class="${active===r?'active':''}" href="#${r}"><div>${icon(r)}</div>${l}</a>`).join('')}</nav>`; }
function layout(content,active='home'){ return `<div class="shell">${topbar(active)}${content}${mobileNav(active)}</div>`; }
function videoCard(v){ return `<article class="card" onclick="navigate('watch/${v.id}')"><div class="card-media"><img src="${v.image||DEFAULT_IMG}" alt="${v.title}"><span class="pill">${v.access}</span><span class="pill duration">${v.duration} min</span></div><div class="card-body"><h3 class="card-title">${v.title}</h3><div class="meta">${v.level} · ${v.category}</div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:13px"><strong>${money(v.price)}</strong><span>${state.completed.includes(v.id)?'✓ Completed':'Watch →'}</span></div></div></article>`; }
function programCard(p){ return `<article class="card" onclick="navigate('program/${p.id}')"><div class="card-media"><img src="${p.image||DEFAULT_IMG}" alt="${p.title}"><span class="pill">${p.days} days</span></div><div class="card-body"><h3 class="card-title">${p.title}</h3><p class="meta">${p.subtitle}</p><div class="progress"><span style="width:${state.progress[p.id]||0}%"></span></div><div style="display:flex;justify-content:space-between;margin-top:10px"><span class="meta">${state.progress[p.id]||0}% complete</span><strong>${money(p.price)}</strong></div></div></article>`; }

function home(){
  const featured=state.programs.slice(0,3).map(programCard).join('');
  const recommended=state.videos.slice(0,3).map(videoCard).join('');
  return layout(`<main class="page"><section class="hero"><div class="hero-copy"><span class="eyebrow">Your practice, your rhythm</span><h1>Move better.<br>Feel calmer.<br>Live stronger.</h1><p class="lead">Guided yoga classes and structured programs designed to fit real life—from five-minute resets to complete journeys.</p><div class="actions"><button class="btn btn-primary" onclick="navigate('explore')">Start practising</button><button class="btn btn-secondary" onclick="navigate('programs')">Explore programs</button></div></div><div class="hero-media"><img src="${state.heroImage}" alt="Yoga instructor outdoors"></div></section>
  <section class="section"><div class="section-head"><div><span class="eyebrow">Pick up where you left off</span><h2>Continue your practice</h2></div><a class="text-link" href="#practice">View progress</a></div><div class="grid grid-3">${recommended}</div></section>
  <section class="section"><div class="section-head"><div><span class="eyebrow">Guided journeys</span><h2>Featured programs</h2></div><a class="text-link" href="#programs">View all</a></div><div class="grid grid-3">${featured}</div></section>
  <section class="section"><div class="section-head"><div><span class="eyebrow">Made for your needs</span><h2>Browse by goal</h2></div></div><div class="goal-grid">${[['◯','Flexibility'],['☁','Stress Relief'],['◇','Strength'],['☾','Better Sleep'],['↟','Posture'],['☀','Morning Energy']].map(x=>`<div class="goal"><span style="font-size:24px">${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div></section></main>`,'home');
}

function explore(){
 return layout(`<main class="page"><div class="page-title"><div><span class="eyebrow">Find your next class</span><h1>Explore</h1><p class="lead">Choose by time, level, style or goal.</p></div></div><div class="searchbar">⌕<input id="search" placeholder="Search classes..." oninput="filterClasses()"></div><div class="filters"><select id="level" onchange="filterClasses()"><option value="">All levels</option><option>Beginner</option><option>Intermediate</option></select><select id="category" onchange="filterClasses()"><option value="">All styles</option><option>Morning</option><option>Vinyasa</option><option>Mobility</option><option>Restorative</option></select><select id="access" onchange="filterClasses()"><option value="">All access</option><option>Free</option><option>Paid</option></select></div><div id="class-list" class="class-list">${classRows(state.videos.filter(v=>v.published))}</div></main>`,'explore');
}
function classRows(list){ return list.length?list.map(v=>`<article class="class-row"><img src="${v.image}" alt="${v.title}"><div><h3>${v.title}</h3><div class="meta">${v.duration} min · ${v.level} · ${v.category}</div><p class="meta" style="margin:7px 0 0">${v.description}</p></div><div class="row-actions"><div class="price">${money(v.price)}</div><button class="btn btn-primary btn-small" onclick="navigate('watch/${v.id}')">${v.price===0?'Watch':'View'}</button></div></article>`).join(''):`<div class="empty">No classes match those filters.</div>`; }
window.filterClasses=()=>{ const q=document.querySelector('#search').value.toLowerCase(),level=document.querySelector('#level').value,cat=document.querySelector('#category').value,acc=document.querySelector('#access').value; const list=state.videos.filter(v=>v.published&&(!q||(v.title+' '+v.description).toLowerCase().includes(q))&&(!level||v.level===level)&&(!cat||v.category===cat)&&(!acc||v.access===acc)); document.querySelector('#class-list').innerHTML=classRows(list); };

function programs(){ return layout(`<main class="page"><div class="page-title"><div><span class="eyebrow">Follow a clear path</span><h1>Programs</h1><p class="lead">Structured courses that take you from the first session to a real result.</p></div></div><div class="grid grid-3">${state.programs.map(programCard).join('')}</div></main>`,'programs'); }
function programDetail(id){ const p=state.programs.find(x=>x.id===id); if(!p)return notFound(); const lessons=p.lessonIds.map(id=>state.videos.find(v=>v.id===id)).filter(Boolean); const owned=state.purchases.includes(p.id); return layout(`<main class="page"><section class="detail-hero"><img src="${p.image}" alt="${p.title}"><div class="detail-copy"><span class="pill" style="color:#26212e">${p.level} · ${p.days} days</span><h1>${p.title}</h1><p class="lead">${p.subtitle}</p></div></section><div class="detail-layout"><section class="panel"><h2>About this program</h2><p class="lead" style="font-size:16px">${p.description}</p><h3>Program lessons</h3>${lessons.map((v,i)=>`<div class="lesson" onclick="${owned?`navigate('watch/${v.id}')`:''}"><div class="lesson-num">${i+1}</div><div style="flex:1"><strong>${v.title}</strong><div class="meta">${v.duration} min · ${v.level}</div></div><span>${owned?'▶':'🔒'}</span></div>`).join('')}</section><aside class="panel" style="height:max-content;position:sticky;top:95px"><span class="eyebrow">Lifetime access</span><h2 style="margin:10px 0">${money(p.price)}</h2><p class="meta">Includes ${lessons.length} guided classes, progress tracking and future updates.</p><button class="btn btn-primary" style="width:100%;margin-top:12px" onclick="buyProgram('${p.id}')">${owned?'Start program':'Buy program'}</button></aside></div></main>`,'programs'); }
window.buyProgram=(id)=>{ if(!state.purchases.includes(id)){state.purchases.push(id);save();toast('Program added to your library (demo checkout).');render();} else { const p=state.programs.find(x=>x.id===id); navigate('watch/'+p.lessonIds[0]); } };

async function watch(id){ const v=state.videos.find(x=>x.id===id); if(!v)return notFound(); let media=''; if(v.videoKey){ try{ const blob=await getMedia(v.videoKey); if(blob){const url=URL.createObjectURL(blob);objectUrls.push(url);media=`<video controls playsinline poster="${v.image}"><source src="${url}" type="${blob.type}">Your browser cannot play this video.</video>`;} }catch{} }
 if(!media) media=`<div class="player-placeholder" style="background-image:linear-gradient(rgba(20,16,28,.58),rgba(20,16,28,.82)),url('${v.image}');background-size:cover;background-position:center"><div><div style="font-size:58px">▶</div><h2>Video preview</h2><p>This demo class has no video uploaded yet.<br>Open Admin → Add Video to attach one from your device.</p></div></div>`;
 document.querySelector('#app').innerHTML=layout(`<main class="page"><div class="page-title"><div><span class="eyebrow">${v.category}</span><h1 style="font-size:clamp(34px,5vw,55px)">${v.title}</h1><p class="meta">${v.duration} minutes · ${v.level}</p></div></div><div class="player-shell">${media}</div><div class="player-info"><section class="panel"><h2>About this class</h2><p class="lead" style="font-size:16px">${v.description}</p><div class="actions"><button class="btn btn-primary" onclick="completeVideo('${v.id}')">${state.completed.includes(v.id)?'✓ Completed':'Mark as complete'}</button><button class="btn btn-secondary" onclick="toggleFavourite('${v.id}')">${state.favourites.includes(v.id)?'♥ Saved':'♡ Add to favourites'}</button></div></section><aside class="panel"><span class="eyebrow">Up next</span><h3>${state.videos[(state.videos.indexOf(v)+1)%state.videos.length].title}</h3><button class="btn btn-secondary" style="width:100%" onclick="navigate('watch/${state.videos[(state.videos.indexOf(v)+1)%state.videos.length].id}')">Next class →</button></aside></div></main>`,'explore'); }
window.completeVideo=(id)=>{ if(!state.completed.includes(id))state.completed.push(id); save();toast('Class marked complete.');render(); };
window.toggleFavourite=(id)=>{ state.favourites=state.favourites.includes(id)?state.favourites.filter(x=>x!==id):[...state.favourites,id];save();toast('Favourites updated.');render(); };

function practice(){ const purchased=state.programs.filter(p=>state.purchases.includes(p.id)); const fav=state.videos.filter(v=>state.favourites.includes(v.id)); return layout(`<main class="page"><div class="page-title"><div><span class="eyebrow">Your personal studio</span><h1>My Practice</h1></div></div><div class="stats"><div class="stat"><strong>${state.completed.length}</strong><span class="meta">Classes</span></div><div class="stat"><strong>${state.completed.reduce((s,id)=>s+(state.videos.find(v=>v.id===id)?.duration||0),0)}</strong><span class="meta">Minutes</span></div><div class="stat"><strong>3</strong><span class="meta">Practice days</span></div><div class="stat"><strong>🔥 3</strong><span class="meta">Day streak</span></div></div><section class="section"><div class="section-head"><h2>Purchased programs</h2></div><div class="grid grid-3">${purchased.length?purchased.map(programCard).join(''):'<div class="empty">Your purchased programs will appear here.</div>'}</div></section><section class="section"><div class="section-head"><h2>Favourites</h2></div><div class="grid grid-3">${fav.length?fav.map(videoCard).join(''):'<div class="empty">Save classes you want to practise again.</div>'}</div></section></main>`,'practice'); }
function profile(){ return layout(`<main class="page"><div class="page-title"><div><span class="eyebrow">Account</span><h1>Profile</h1></div></div><div class="detail-layout"><section class="panel"><div style="display:flex;align-items:center;gap:18px"><img class="avatar" style="width:78px;height:78px" src="${state.heroImage}"><div><h2 style="margin-bottom:4px">Emma</h2><span class="meta">Member since May 2026</span></div></div><div style="margin-top:25px">${['My account','Membership','Purchases','Payment methods','Goals & preferences','Settings','Help & support'].map(x=>`<div class="lesson"><strong style="flex:1">${x}</strong><span>›</span></div>`).join('')}</div></section><aside class="panel"><span class="eyebrow">Creator access</span><h3>Manage your studio</h3><p class="meta">Upload classes, replace pictures and build programs.</p><button class="btn btn-primary" onclick="navigate('admin')">Open admin</button></aside></div></main>`,'profile'); }

function admin(section='dashboard'){
 const side=[['dashboard','Dashboard'],['videos','Videos'],['upload','Add video'],['programs','Programs'],['site','Site images']];
 const content=section==='dashboard'?adminDashboard():section==='videos'?adminVideos():section==='upload'?adminUpload():section==='site'?adminSite():adminPrograms();
 return `<div class="admin-shell"><aside class="sidebar"><a class="brand" href="#home"><span class="brand-mark">Y</span><span>Yoga Admin</span></a><nav class="side-nav">${side.map(([r,l])=>`<a class="${section===r?'active':''}" href="#admin/${r}">${icon(r)} ${l}</a>`).join('')}<a href="#home">← View website</a></nav></aside><main class="admin-main">${content}</main></div>`;
}
function adminDashboard(){ return `<div class="admin-top"><div><span class="eyebrow">Studio overview</span><h1>Dashboard</h1></div><button class="btn btn-primary" onclick="navigate('admin/upload')">+ Add video</button></div><div class="admin-grid"><div class="admin-stat"><span>Total sales</span><strong>CHF 5,890</strong></div><div class="admin-stat"><span>Orders</span><strong>128</strong></div><div class="admin-stat"><span>Active members</span><strong>312</strong></div><div class="admin-stat"><span>Video views</span><strong>4,892</strong></div></div><section class="section"><div class="section-head"><h2>Recent content</h2><a class="text-link" href="#admin/videos">Manage all</a></div>${videoTable(state.videos.slice(0,5))}</section>`; }
function videoTable(list){ return `<div class="table-wrap"><table><thead><tr><th>Class</th><th>Level</th><th>Access</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody>${list.map(v=>`<tr><td><div style="display:flex;align-items:center;gap:12px"><img class="thumb" src="${v.image}"><strong>${v.title}</strong></div></td><td>${v.level}</td><td>${v.access}</td><td>${money(v.price)}</td><td>${v.published?'Published':'Draft'}</td><td><button class="btn btn-secondary btn-small" onclick="editVideo('${v.id}')">Edit</button> <button class="btn btn-danger btn-small" onclick="removeVideo('${v.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`; }
function adminVideos(){ return `<div class="admin-top"><div><span class="eyebrow">Content library</span><h1>Videos</h1></div><button class="btn btn-primary" onclick="navigate('admin/upload')">+ Add video</button></div>${videoTable(state.videos)}`; }
function adminPrograms(){ return `<div class="admin-top"><div><span class="eyebrow">Course builder</span><h1>Programs</h1></div><button class="btn btn-primary" onclick="toast('Program builder is ready for the next sprint.')">+ New program</button></div><div class="grid grid-3">${state.programs.map(programCard).join('')}</div><div class="empty" style="margin-top:20px">This MVP displays programs. Drag-and-drop lesson editing can be connected in the next version.</div>`; }
function adminSite(){ return `<div class="admin-top"><div><span class="eyebrow">Brand content</span><h1>Site images</h1></div></div><section class="panel"><h2>Homepage hero image</h2><p class="meta">Choose a new picture from your phone or computer. It updates the homepage and profile immediately.</p><div class="upload-box"><img src="${state.heroImage}" alt="Current hero"></div><div class="actions"><label class="btn btn-primary" for="hero-picker">Change picture</label><input id="hero-picker" type="file" accept="image/*" hidden onchange="changeHero(this.files[0])"><button class="btn btn-secondary" onclick="resetHero()">Restore original</button></div></section>`; }
function adminUpload(editId=''){ const v=editId?state.videos.find(x=>x.id===editId):null; return `<div class="admin-top"><div><span class="eyebrow">${v?'Edit class':'New content'}</span><h1>${v?'Edit video':'Upload new video'}</h1></div></div><form class="panel" onsubmit="saveVideoForm(event,'${editId}')"><div class="form-grid"><div class="field full"><label>Cover image</label><div id="cover-preview" class="upload-box">${v?`<img src="${v.image}">`:'<div><div style="font-size:40px">▧</div><strong>Upload a cover picture</strong><p class="meta">JPG, PNG or WEBP</p></div>'}</div><input id="cover" type="file" accept="image/*" onchange="previewCover(this.files[0])"></div><div class="field full"><label>Video file</label><div class="upload-box" style="min-height:140px"><div><div style="font-size:40px">▷</div><strong>${v?.videoKey?'A video is already attached':'Choose a video from your device'}</strong><p class="meta">MP4, MOV or browser-supported video. Stored locally in this prototype.</p></div></div><input id="videoFile" type="file" accept="video/*"></div><div class="field"><label>Title</label><input id="title" required value="${v?.title||''}" placeholder="Morning Full-Body Flow"></div><div class="field"><label>Duration (minutes)</label><input id="duration" type="number" min="1" required value="${v?.duration||20}"></div><div class="field full"><label>Description</label><textarea id="description" rows="4" required>${v?.description||''}</textarea></div><div class="field"><label>Level</label><select id="level"><option ${v?.level==='Beginner'?'selected':''}>Beginner</option><option ${v?.level==='Intermediate'?'selected':''}>Intermediate</option><option ${v?.level==='Advanced'?'selected':''}>Advanced</option><option ${v?.level==='All Levels'?'selected':''}>All Levels</option></select></div><div class="field"><label>Category</label><select id="category"><option>Morning</option><option>Vinyasa</option><option>Mobility</option><option>Restorative</option><option>Strength</option><option>Meditation</option></select></div><div class="field"><label>Access</label><select id="access" onchange="document.querySelector('#price').disabled=this.value==='Free'"><option ${v?.access==='Free'?'selected':''}>Free</option><option ${v?.access==='Paid'?'selected':''}>Paid</option><option ${v?.access==='Membership'?'selected':''}>Membership</option></select></div><div class="field"><label>Price (CHF)</label><input id="price" type="number" min="0" step="1" value="${v?.price||0}"></div><div class="field"><label>Status</label><select id="published"><option value="true" ${v?.published!==false?'selected':''}>Published</option><option value="false" ${v?.published===false?'selected':''}>Draft</option></select></div></div><div class="actions" style="justify-content:flex-end"><button type="button" class="btn btn-secondary" onclick="navigate('admin/videos')">Cancel</button><button class="btn btn-primary" type="submit">${v?'Save changes':'Publish video'}</button></div></form>`; }

window.previewCover=async file=>{ if(!file)return; const url=await fileToDataUrl(file); document.querySelector('#cover-preview').innerHTML=`<img src="${url}">`; document.querySelector('#cover-preview').dataset.url=url; };
window.changeHero=async file=>{ if(!file)return; state.heroImage=await fileToDataUrl(file); save();toast('Homepage picture updated.');render(); };
window.resetHero=()=>{state.heroImage=DEFAULT_IMG;save();render();};
window.editVideo=id=>{location.hash='#admin/upload?edit='+id;};
window.removeVideo=async id=>{ const v=state.videos.find(x=>x.id===id); if(!confirm(`Delete “${v.title}”?`))return; await deleteMedia(v.videoKey); state.videos=state.videos.filter(x=>x.id!==id); state.programs.forEach(p=>p.lessonIds=p.lessonIds.filter(x=>x!==id)); save();toast('Video deleted.');render(); };
window.saveVideoForm=async(e,editId)=>{e.preventDefault(); const old=editId?state.videos.find(x=>x.id===editId):null; const cover=document.querySelector('#cover-preview').dataset.url || old?.image || DEFAULT_IMG; const file=document.querySelector('#videoFile').files[0]; let videoKey=old?.videoKey||null; if(file){ if(old?.videoKey)await deleteMedia(old.videoKey); videoKey='video-'+Date.now(); await putMedia(videoKey,file); }
 const access=document.querySelector('#access').value; const item={id:old?.id||'v'+Date.now(),title:document.querySelector('#title').value.trim(),duration:Number(document.querySelector('#duration').value),description:document.querySelector('#description').value.trim(),level:document.querySelector('#level').value,category:document.querySelector('#category').value,goal:document.querySelector('#category').value,access,price:access==='Free'?0:Number(document.querySelector('#price').value||0),published:document.querySelector('#published').value==='true',image:cover,videoKey};
 if(old)state.videos=state.videos.map(x=>x.id===old.id?item:x); else state.videos.unshift(item); save(); toast(old?'Video updated.':'Video published.'); navigate('admin/videos'); };

function notFound(){ return layout(`<main class="page"><div class="empty"><h2>Page not found</h2><button class="btn btn-primary" onclick="navigate('home')">Back home</button></div></main>`); }
async function render(){ objectUrls.forEach(URL.revokeObjectURL);objectUrls=[]; const [r,id]=route(); let html; if(r==='home')html=home(); else if(r==='explore')html=explore(); else if(r==='programs')html=programs(); else if(r==='program')html=programDetail(id); else if(r==='watch'){ document.querySelector('#app').innerHTML=layout('<main class="page"><div class="empty">Loading video…</div></main>','explore'); await watch(id); return; } else if(r==='practice')html=practice(); else if(r==='profile')html=profile(); else if(r==='admin'){ let section=id||'dashboard'; const full=location.hash; const edit=full.match(/edit=([^&]+)/)?.[1]; html=edit?admin('upload').replace(adminUpload(),adminUpload(edit)):admin(section); if(edit) html=admin('upload').replace(adminUpload(),adminUpload(edit)); } else html=notFound(); document.querySelector('#app').innerHTML=html; window.scrollTo(0,0); }
window.addEventListener('hashchange',render); window.addEventListener('DOMContentLoaded',render);
